version: "3.2"

services:

  krill:
    container_name: krill-springboot
    image: adoptopenjdk/openjdk11:alpine-jre
    volumes:
      - ../krill/target/:/app
    command: java -jar /app/krill-0.0.1-SNAPSHOT.jar
    ports:
      - 8282:8080
    environment:
      - JDBC=jdbc:mysql://172.23.0.2:3306/krill
      - MYSQL_USER=root
      - MYSQL_PASS=ANf3Mgx6nseCbZpu


networks:
  default:
    external:
      name: databases_default_network